# Generated by Django 4.1 on 2022-09-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                ("song_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=2000)),
                ("singer", models.CharField(max_length=2000)),
                ("tags", models.CharField(max_length=2000)),
                ("image", models.ImageField(upload_to="document")),
                ("song", models.FileField(upload_to="document")),
            ],
        ),
    ]
